apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: example-sql-instance
  namespace: osba-demo
spec:
  clusterServiceClassExternalName: azure-sql-12-0
  clusterServicePlanExternalName: standard
  parameters:
    location: eastus
    resourceGroup: osbademo
    dtus: 20
    firewallRules:
    - startIPAddress: "0.0.0.0"
      endIPAddress: "255.255.255.255"
      name: "AllowAll"

---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: example--sql-12-0-binding
  namespace: osba-demo
spec:
  instanceRef:
    name: example-sql-instance
  secretName: example-sql-secret