apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: demo-sql-instance
  namespace: osba-demo-live
spec:
  clusterServiceClassExternalName: azure-sql-12-0
  clusterServicePlanExternalName: standard
  parameters:
    location: eastus
    resourceGroup: osbademolive
    dtus: 20
    firewallRules:
    - startIPAddress: "0.0.0.0"
      endIPAddress: "255.255.255.255"
      name: "AllowAll"

---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: demo-sql-12-0-binding
  namespace: osba-demo-live
spec:
  instanceRef:
    name: demo-sql-instance
  secretName: demo-sql-secret