apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-flex-kv-podid
    aadpodidbinding: kvflex-binding
  name: nginx-flex-kv-podid
spec:
  containers:
  - name: nginx-flex-kv-podid
    image: nginx
    volumeMounts:
    - name: test
      mountPath: /kvmnt
      readOnly: true
  volumes:
  - name: test
    flexVolume:
      driver: "azure/kv"
      options:
        usepodidentity: "true"         # [OPTIONAL] if not provided, will default to "false"
        keyvaultname: "AKSDemoKv"               # the name of the KeyVault
        keyvaultobjectnames: "SuperSecretURL"        # list of KeyVault object names (semi-colon separated)
        keyvaultobjecttypes: secret    # list of KeyVault object types: secret, key or cert (semi-colon separated)
        keyvaultobjectversions: ""     # [OPTIONAL] list of KeyVault object versions (semi-colon separated), will get latest if empty
        resourcegroup: "AKSAzureDemo"              # [REQUIRED FOR < v0.0.14] the resource group of the KeyVault
        subscriptionid: "469048f1-92af-4c71-a63b-330ec31d2b82"             # [REQUIRED FOR < v0.0.14] the subscription ID of the KeyVault
        tenantid: "8f18eb27-4f87-4a88-b325-f8e6e7e43486"                   # the tenant ID of the KeyVault